#general setup
TILE_SIZE = 64
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
ANIMATION_SPEED = 8

EDITOR_DATA = {

}

SKY_COLOR,SEA_COLOR,HORIZON_COLOR,HORIZON_TOP_COLOR,LINE_COLOR = '#ddc6a1','#92a9ce','#f5f1de','#d1aa9d','black'

